language: generic
matrix:
  include:
    - os: osx
      osx_image: xcode10
      script:
        - swift test
        
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swiftenv global 4.2
      script:
        - swift test

    - os: osx
      name: After Before test
      osx_image: xcode10
      script:
        - swift build
